name: Deploy AI Project

on:
  push:
    branches:
      - main

env:
  REPLICATE_URL: 'https://api.replicate.com/v1/predictions'
  REPLICATE_API_TOKEN: 'r8_dn5MfBHwgVLRSQgK949fOGbdnmT2HSp1ZBse6'
  REPLICATE_MODEL_ID: '2b017d9b67edd2ee1401238df49d75da53c523f36e363881e057f5dc3ed3c5b2'
  S3_BUCKET: 'rapid-api'
  AI_MODEL_NAME: 'stability-ai'
  DIRECTORY_NAME: 'images'

jobs:    
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v3
    - name: Run linting rules and tests
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - run: npm install 
    - run: serverless plugin install -n serverless-dotenv-plugin
    - run: serverless plugin install -n serverless-plugin-common-excludes
    - run: serverless plugin install -n serverless-functions-base-path
    - run: serverless plugin install -n serverless-python-requirements
    - run: serverless plugin install -n serverless-lift
    - run: serverless plugin install -n serverless-offline  
    
    
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
